### ISSUE TITLE
Practical react example?

### ISSUE THREAD

**Issue by DarrylD** [adjohnson916/firedux#11]
Hard to picture how to use this at scale, any way to get a decent example explaining how to do so?

**Comment by adjohnson916** [comment]
@DarrylD Thanks for your interest. I don't have any public examples yet. I'm starting a TodoMVC implementation (https://github.com/adjohnson916/firedux-todomvc), but it's not finished yet. I'll try to update you on any progress.

Related to #9.

**Comment by adjohnson916** [comment]
@DarrylD I've completed the TodoMVC example (https://github.com/adjohnson916/firedux-todomvc).

**Comment by DarrylD** [comment]
Awesome! I'll take a look, thx!
