### ISSUE TITLE
Best practice to handle incoming watched paths

### ISSUE THREAD

**Issue by DarrylD** [adjohnson916/firedux#13]
I have a `watch` for a path. Like the docs said, it will only resolve once (the first time). Is their a good practice to handle all new entries from that watch path?

Ex: for each new entry that get added, fire an action creator.

Please excuse my ignorance :)

**Comment by adjohnson916** [comment]
@DarrylD It's only the promise that resolves once. A watch will trigger a store dispatch on every Firebase value chamge at the watched path, which should cause your reducers to re-runupdating, the local stateallowing, and causing a re-reunder as needed or allow your components to react to those changes.

**Comment by DarrylD** [comment]
Made some middleware to handle it, working ok at the moment, thanks!

**Comment by adjohnson916** [comment]
@DarryID Please do share if you're able!

**Comment by DarrylD** [comment]
Fairly new to react/redux so excuse me if this is a crappy implementation :)

I have this in my container
```
componentDidMount() {
  firedux.watch('newMessage')
}
```

and this added to my middleware
```
export default store => next => action  => {
    if (action.path && action.path === 'newMessage') {
        store.dispatch( actions.getMessages() )
    }
    return next(action)
}
```
