### ISSUE TITLE
Update updeep dependency to latest version

### ISSUE THREAD

**Issue by uneart** [adjohnson916/firedux#14]
There seems to be a problem with the currently used npm package updeep@0.11.0 which requires an old peer of lodash (v3.0.0).
Using gulp with Browserify and a newer version of lodash creates a lot of "Cannot find module lodash/collection/......" errors for me. The latest version of updeep requires at least lodash@4.2.0 so updating to the latest updeep version should fix that.

Installing the latest version 0.14.0 of updeep as a root dependency in my project fixed it for me.

**Comment by adjohnson916** [comment]
@uneart Updated and published as `0.6.3`. Thanks!
