### ISSUE TITLE
Dynamic Firebase ref url with React router params instead of url matching

### ISSUE THREAD

**Issue by uneart** [adjohnson916/firedux#18]
Hello,

in the TodoMVC example, the actual Firebase url is fetched by matching the session key from `window.location` so that every time the page loads Firedux only gets access to the current session data in Firebase.

I have a React router param `groupId` accessible within the App as `this.props.params.groupId` and want to use that in the url e.g. `url: FIREBASEURL + this.props.params.groupId`. It just won't work.

The problem seems to be that Firedux is created first within the Redux store when calling `firedux.dispatch = store.dispatch` so way before the router params are even accessible and therefore no reference to the props.

The React App is Rendered as:
```
<Provider store={store}>
    <Router history={history}>
    <Route path="/" component={App}>
        <IndexRoute component={Home}/>
        <Route path="group/:groupId" component={Tool}/>
        <Route path="*" component={NotFound}/>
    </Route>
    </Router>
</Provider>
```

Any ideas how to solve this?

**Comment by adjohnson916** [comment]
@uneart Can you just initialize Firedux with the top-level Firebase URL, then interact with it in components on paths that include the appropriate parameters?

**Comment by uneart** [comment]
@adjohnson916 That is what I ended up doing now as a workaround. I was just wondering if there is any way to achieve this. Fetching it from window.location doesn't work well with React router.

**Comment by adjohnson916** [comment]
@uneart Maybe someday I'll change the TodoMVC example to use React Router.
