### ISSUE TITLE
Missing url in doc for config?

### ISSUE THREAD

**Issue by DarrylD** [adjohnson916/firedux#45]
I needed this property, the doc may need an update?

```
/**
 * Then create your Firedux instance, passing it your database reference as `ref`.
 */
const firedux = new Firedux({
  ref,
  url: 'http://somethin....' <-- missing but needed?

  // Optional:
  omit: ['$localState'] // Properties to reserve for local use and not sync with Firebase.
})
```

**Comment by adjohnson916** [comment]
@DarrylD What version of Firebase and firedux are you using here?

**Comment by DarrylD** [comment]
@adjohnson916 `0.6.4`

**Comment by adjohnson916** [comment]
@DarrylD And Firebase version?

**Comment by DarrylD** [comment]
Sorry about that, `3.2.1`

**Comment by adjohnson916** [comment]
@DarrylD It's recommended now to pass `ref` instead of `url` which isn't supported for Firebase 3.x anyway. I've added a deprecation warning in the code.

**Comment by adjohnson916** [comment]
@DarrylD Please install `0.6.5` for improved Firebase v3 support - see https://github.com/adjohnson916/firedux/issues/12#issuecomment-238060907.
