### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by prabhaav** [adjohnson916/firedux#51]
Hi, does this library support react-native? I am seeing the following error when I try to use it in my app:

> TransformError: /Users/prabhaav/Development/betaApp/node_modules/firedux/dist/src/index.js: Couldn't find preset "es2015" relative to directory "/Users/prabhaav/Development/betaApp/node_modules/firedux"

I manually installed babel: npm install babel-cli babel-preset-es2015 

Then I see the following error:

![screen shot 2016-08-17 at 10 13 24 am](https://cloud.githubusercontent.com/assets/11723563/17746091/60e17aa2-6463-11e6-9024-52c508302601.png)

Anybody else facing this issue?

**Comment by prabhaav** [comment]
Got around above issue with the following fix: 

> echo node_modules/firebase/lib/firebase-web.js > .babelignore

However, it's now breaking here:

![screen shot 2016-08-17 at 10 36 20 am](https://cloud.githubusercontent.com/assets/11723563/17746769/81e6a03a-6466-11e6-8740-110148ccd4df.png)

**Comment by adjohnson916** [comment]
@prabhaav I've not ever used the Firebase client from React Native, so can't tell you whether it  will work, but I've just updated the dependency to not assume existence of `Image`.
