### ISSUE TITLE
Phantom database for deployed app

### ISSUE THREAD

**Issue by Dooblr** [adjohnson916/firedux#52]
Localhost dev app is talking to the right Firebase backend and displaying new data in the database tree in the dashboard/console as it should--

The deployed app however _is_ persisting data, but not the same place as the localhost. When I use $ firebase open database or whatever, it says it's pointing to the same address, but not displaying the same database tree as the localhost, which I would expect.

So the app is functional, but I have no idea where my data is, which is a little concerning :p

Anyone else run into this?

**Comment by adjohnson916** [comment]
@Dooblr Is your source code available somewhere for us to take a look? I can't tell what you're experiencing, but would be surprised if firedux had anything to do with it.

**Comment by Dooblr** [comment]
Not sure where that code went. Had success with a vanilla FB config so I'm going to go in that direction for a bit. Will reopen if I decide to switch back. Thanks!
