### ISSUE TITLE
Currently unusable

### ISSUE THREAD

**Issue by matthewconstantine** [adjohnson916/firedux#6]
I'm getting a similar issue to the one reported in #3. I'm on `"firedux": "^0.6.1",` which I installed today. 

The code example below errors out with a `Uncaught TypeError: _firedux2.default is not a function` error. `_firedux2.default` seems to be an empty object. 

```javascript
import Firedux from 'firedux'
const firedux = new Firedux({
  url: 'https://redux-firebase.firebaseio.com/',

  // Optional:
  omit: ['$localState'] // Properties to reserve for local use and not sync with Firebase.
})
```

Let me know if there's anything I can do to help. I'm excited to give this shot.

**Comment by adjohnson916** [comment]
@matthewconstantine Thanks for reporting. But I'm not able to reproduce your issue here with firedux `0.6.1` and node `5.4.0`. Can you double-check your `package.json`, try deleting `node_modules`, run `npm cache clear` then `npm install` again? If after that it's still happening, can you give me your `npm ls` output and `node -v`?

**Comment by matthewconstantine** [comment]
Thanks for the response. I was on node `4.2.6` when I tried it. I just upgraded to `5.4.0`, and did a `rm -rf node_modules && npm cache clear && npm install`. Restarted the server and I'm seeing the same issue. Here's my `npm ls`: https://gist.github.com/matthewconstantine/4fe57027a887ea877646.

**Comment by adjohnson916** [comment]
@matthewconstantine Sorry about that. Actually if you run `npm shrinkwrap` then give me the resulting `npm-shrinkwrap.json` file, it'll be easier for me to try to reproduce. Or even better if you push your whole project up somewhere, I can take a look. I wonder how you're compiling the ES6 , e.g. and Babel presets or plugins that I'm not using.

**Comment by matthewconstantine** [comment]
@adjohnson916 No problem. I threw together [a repo demonstrating the issue](https://github.com/matthewconstantine/firedux-test). I generated it with the [yeoman webpack react generator](https://github.com/newtriks/generator-react-webpack) using the default settings, like I did on my main project. And added firedux [in the generated default component](https://github.com/matthewconstantine/firedux-test/blob/master/src/components/Main.js#L7-L8), a non-sensical place but it demonstrates the problem. I skipped installing redux itself just to keep the demonstration simple. I hope you see the same thing I am, let me know if there's anything I can do to help.

**Comment by adjohnson916** [comment]
@matthewconstantine Oh I see, it's using the `browser` path instead of `main` in `package.json`. I've removed that with `0.6.2` and published - want to give it a shot?

P.S. I bet you know this, but with your test project you aren't passing the required `url` option.

**Comment by matthewconstantine** [comment]
Thanks for the fix! I'll give it a shot. And yep, I knew about the `url` option, just skipped it for the test.

**Comment by adjohnson916** [comment]
@matthewconstantine Cool, please let me know if it works! And any other feedback on this project!
