### ISSUE TITLE
get data once

### ISSUE THREAD

**Issue by kuronaru** [adjohnson916/firedux#79]
so i have array of keys for `answers`:

`const arryKeys = ['answer1', 'answer2']`

my data structure looks like this:
```
questions {
  name: 'test',
  answers: {
    answer1: true,
    answer2: true
  }
}

answers {
  answer1 {
    name: 'Yes'
  }
  answer2 {
    name: 'No'
  }
}
```

i tried to do this to get the actual answers value on `answers`
```
arryKeys.map((aK) => {
  firedux.get(`users/${aK}`)
})
```

i'm not sure what's the best way to do it, hope someone can help me, thanks

**Comment by adjohnson916** [comment]
@kuronaru It's hard to say what your specific issue is without more details, but did you notice you have `users` instead of `answers`? Try this:
```
arryKeys.map((aK) => {
  firedux.get(`answers/${aK}`)
})
```

**Comment by kuronaru** [comment]
sorry for the confusion, i was able to figure it out now. thanks :)
