### ISSUE TITLE
Firedux API from component

### ISSUE THREAD

**Issue by lukehedger** [adjohnson916/firedux#8]
@jonathandion mentioned in https://github.com/adjohnson916/firedux/issues/7#issuecomment-192968803

What's the best way to access the Firedux API from a component (ie. outside of the file where the `store` was created)? Even if a new Firebase ref is created in the component, Firedux still needs the `store.dispatch` method. And `state.firedux` is just the returned data, no access to the API from there.

Thanks for your help. Nice library!

**Comment by adjohnson916** [comment]
@lukehedger This module is meant to be used in apps with the Flux architecture encouraged by Redux, where the only way to change state is to dispatch actions via `store.dispatch(action)`, which you should be able to do from your components as long as you can import your store there. I might add some documentation around this. Let me know if that doesn't make sense.
