### ISSUE TITLE
help: login

### ISSUE THREAD

**Issue by kuronaru** [adjohnson916/firedux#81]
i'm trying out the snippet provided for logging in.

```
handleLogin (e) {
    e.preventDefault()
    const em = this.email.value
    const pw = this.pw.value

    console.log('em', em, 'pw', pw)
    firedux.login({em, pw})
}
```

and i got this error: 
weird thing is that it's just email, password auth but the error log said it's related to FB auth

![screen shot 2016-11-21 at 8 44 22 pm](https://cloud.githubusercontent.com/assets/5925092/20483168/98353eee-b02b-11e6-966f-6f81cae10cec.png)

can someone provide a example repo using firedux for auth? would really appreciate it, thanks

**Comment by adjohnson916** [comment]
@kuronaru Are you using Firebase 3? The login methods aren't really fleshed out yet even for Firebase 2. I might recommend managing auth outside of firedux for now. Or pull request! Note that some work was done here #47 but never completed.

**Comment by adjohnson916** [comment]
See also #4.
