### ISSUE TITLE
Any larger examples?

### ISSUE THREAD

**Issue by slightlytyler** [adjohnson916/firedux#9]
Exploring firebase integrations for redux atm and firedux seems to having an interesting approach. Do you have any example applications you can share?

**Comment by adjohnson916** [comment]
@slightlytyler Not yet - maybe it'll be you! I created this right before moving to another existing project that wasn't React from the start.

Any particular questions about the API or how to accomplish certain tasks? Just let me know.

Thanks for your interest!

**Comment by adjohnson916** [comment]
@slightlytyler Per #11, I'm starting a TodoMVC implementation (https://github.com/adjohnson916/firedux-todomvc), but it's not finished yet. I'll try to update you on any progress.

**Comment by adjohnson916** [comment]
@slightlytyler Per #11, I've completed the TodoMVC example (https://github.com/adjohnson916/firedux-todomvc).
